from os import system

try:
	import requests
except:
	system("pip install requests")

try:
	from coloriran import Fore
except:
	system("pip install coloriran")

admin = ("""admin
admin.php
admin.html
admin1.php
admin1.html
admin2.php
admin2.html
login
login.php
login.html
yonetim.php
yonetim.html
yonetici.php
yonetici.html
ccms/
ccms/login.php
ccms/index.php
maintenance/
webmaster/
adm/
configuration/
configure/
websvn/
admin/
admin/account.asp
admin/account.html
admin/account.php
admin/add_banner.php/
admin/addblog.php
admin/add_gallery_image.php
admin/add.php
admin/add-room.php
admin/add-slider.php
admin/add_testimonials.php
admin/admin/
admin/adminarea.php
admin/admin.asp
admin/AdminDashboard.php
admin/admin-home.php
admin/AdminHome.php
admin/admin.html
admin/admin_index.php
admin/admin_login.asp
admin/admin-login.asp
admin/adminLogin.asp
admin/admin_login.html
admin/admin-login.html
admin/adminLogin.html
admin/admin_login.php
admin/admin-login.php
admin/adminLogin.php
admin/admin_management.php
admin/admin.php
admin/admin_users.php
admin/adminview.php
admin/adm.php
admin_area/
adminarea/
admin_area/admin.asp
adminarea/admin.asp
admin_area/admin.html
adminarea/admin.html
admin_area/admin.php
adminarea/admin.php
admin_area/index.asp
adminarea/index.asp
admin_area/index.html
adminarea/index.html
admin_area/index.php
adminarea/index.php
admin_area/login.asp
adminarea/login.asp
admin_area/login.html
adminarea/login.html
admin_area/login.php
adminarea/login.php
admin.asp
admin/banner.php
admin/banners_report.php
admin/category.php
admin/change_gallery.php
admin/checklogin.php
admin/configration.php
admincontrol.asp
admincontrol.html
admincontrol/login.asp
admincontrol/login.html
admincontrol/login.php
admin/control_pages/admin_home.php
admin/controlpanel.asp
admin/controlpanel.html
admin/controlpanel.php
admincontrol.php
admincontrol.php/
admin/cpanel.php
admin/cp.asp
admin/CPhome.php
admin/cp.html
admincp/index.asp
admincp/index.html
admincp/login.asp
admin/cp.php
admin/dashboard/index.php
admin/dashboard.php
admin/dashbord.php
admin/dash.php
admin/default.php
adm/index.asp
adm/index.html
adm/index.php
admin/enter.php
admin/event.php
admin/form.php
admin/gallery.php
admin/headline.php
admin/home.asp
admin/home.html
admin_home.php
admin/home.php
admin.html
admin/index.asp
admin/index-digital.php
admin/index.html
admin/index.php
admin/index_ref.php
admin/initialadmin.php
admin.php
admin.html
admin/cp.php
admin/cp.html
cp.php
cp.html
administrator/
administrator/index.html
administrator/index.php
administrator/login.html
administrator/login.php
administrator/account.html
administrator/account.php
administrator.php
administrator.html
login.php
login.html
modelsearch/login.php
moderator.php
moderator.html
moderator/login.php
moderator/login.html
moderator/admin.php
moderator/admin.html
moderator/
account.php
account.html
controlpanel/
controlpanel.php
controlpanel.html
admincontrol.php
admincontrol.html
adminpanel.php
adminpanel.html
admin1.asp
admin2.asp
yonetim.asp
yonetici.asp
admin/account.asp
admin/index.asp
admin/login.asp
admin/home.asp
admin/controlpanel.asp
admin.asp
admin/cp.asp
cp.asp
administrator/index.asp
administrator/login.asp
administrator/account.asp
administrator.asp
login.asp
modelsearch/login.asp
moderator.asp
moderator/login.asp
moderator/admin.asp
account.asp
controlpanel.asp
admincontrol.asp
adminpanel.asp
fileadmin/
fileadmin.php
fileadmin.asp
fileadmin.html
administration/
administration.php
administration.html
sysadmin.php
sysadmin.html
phpmyadmin/
myadmin/
sysadmin.asp
sysadmin/
ur-admin.asp
ur-admin.php
ur-admin.html
ur-admin/
Server.php
Server.html
Server.asp
Server/
wp-admin/
administr8.php
administr8.html
administr8/
administr8.asp
webadmin/
webadmin.php
webadmin.asp
webadmin.html
administratie/
admins/
admins.php
admins.asp
admins.html
administrivia/
Database_Administration/
WebAdmin/
useradmin/
sysadmins/
admin1/
system-administration/
administrators/
pgadmin/
directadmin/
staradmin/
ServerAdministrator/
SysAdmin/
administer/
LiveUser_Admin/
sys-admin/
typo3/
panel/
cpanel/
cPanel/
cpanel_file/
platz_login/
rcLogin/
blogindex/
formslogin/
autologin/
support_login/
meta_login/
manuallogin/
simpleLogin/
loginflat/
utility_login/
showlogin/
memlogin/
members/
login-redirect/
sub-login/
wp-login/
login1/
dir-login/
login_db/
xlogin/
smblogin/
customer_login/
UserLogin/
login-us/
acct_login/
admin_area/
bigadmin/
project-admins/
phppgadmin/
pureadmin/
sql-admin/
radmind/
openvpnadmin/
wizmysqladmin/
vadmind/
ezsqliteadmin/
hpwebjetadmin/
newsadmin/
adminpro/
Lotus_Domino_Admin/
bbadmin/
vmailadmin/
Indy_admin/
ccp14admin/
irc-macadmin/
banneradmin/
sshadmin/
phpldapadmin/
macadmin/
administratoraccounts/
admin4_account/
admin4_colon/
radmind-1/
Super-Admin/
AdminTools/
cmsadmin/
SysAdmin2/
globes_admin/
cadmins/
phpSQLiteAdmin/
navSiteAdmin/
server_admin_small/
logo_sysadmin/
server/
database_administration/
power_user/
system_administration/
ss_vms_admin_sm/
admins
mail
adm
party
admin
administration
administrator
administrators
database
admin.php
admin.asp
administrator.php
administrator.asp
administrators.asp
administrators.asp
login.php
login.asp
logon.asp
logon.php
quanly.asp
quanly.php
quantri.php
quantri.asp
quantriweb.asp
quantriweb.asp
admin_index.asp
admin_index.php
password.asp
password.php
dangnhap.asp
dangnhap.php
user.php
user.asp
phpinfo.
logs.
log.
adminwww
db.
Readme.
urllist.
admin_file
admin_files
admin_login
cpg
inc_lib
inc_conf
inc_config
lib_config
login
logon
forum
forums
diendan
restricted
forum1
forum2
forum3""").split()


print(Fore.BLUE+""" _     ,_   , , ___,,  ,    _, ___,___,_, 
'|\    | \,|\/|' |  |\ |   (_,' | ' | /_, 
 |-\  _|_/ | `| _|_,|'\|    _) _|_, |'\_  
 '  `'     """)
print(Fore.GREEN+"Chanel Rubika : "+Fore.WHITE+"@Tyro_code"+Fore.GREEN+"     version : "+Fore.WHITE+"1.0\n\n")
print(Fore.RED + '┌─' + Fore.WHITE + '[#]' + Fore.GREEN + ' Enter Your URL (test.ir) : ' + Fore.YELLOW)
url = input(Fore.RED + '└──╼ >>>' + Fore.YELLOW)

print("\n\nstart..")
try:
	for Admin in admin:
		get = requests.get(f"https://"+url+"/"+Admin)
		sits = get.status_code
		if sits == 200:
			print(Fore.BLUE+" [+] "+Fore.GREEN + "https://"+url+"/"+Admin)
		else:
			print(Fore.BLUE+" [-] "+Fore.RED+ "https://"+url+"/"+Admin)
except:
	print(Fore.RED + "\n\n\nError")
